### ISSUE TITLE
clone之后根本就无法编译出执行文件

### ISSUE THREAD

**Issue by netesheng** [joyqi/logecho#5]
clone之后根本就无法编译出执行文件
参照的是http://talk.l4zy.com/t/cong-logechokai-shi-nin-de-jing-tai-bo-ke/96

**Comment by joyqi** [comment]
现在不需要自己来编译了，请参考
http://www.l4zy.com/posts/news-about-logecho.html

**Comment by iyuco** [comment]
404了

**Comment by netesheng** [comment]
嗯
